# runtime: python37
# # service: api
# handlers:
# - url: /static
#   static_dir: static/
# - url: /.*
#   script: auto

runtime: python
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
entrypoint: gunicorn -b :$PORT sales_predictions.wsgi

# beta_settings:
#     cloud_sql_instances: sales-prediction

runtime_config:
  python_version: 3
